// export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const SET_TORNEO = 'SET_TORNEO';
export const FETCH_TORNEO_FAILED = 'FETCH_TORNEO_FAILED';

export const FETCH_EQUIPOS_START = 'FETCH_EQUIPOS_START';
export const FETCH_EQUIPOS_SUCCESS = 'FETCH_EQUIPOS_SUCCESS';
export const FETCH_EQUIPOS_FAIL = 'FETCH_EQUIPOS_FAIL';

export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';