// export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const SET_TORNEO = 'SET_TORNEO';
export const FETCH_TORNEO_FAILED = 'FETCH_TORNEO_FAILED';

export const FETCH_EQUIPOS_START = 'FETCH_EQUIPOS_START';
export const FETCH_EQUIPOS_SUCCESS = 'FETCH_EQUIPOS_SUCCESS';
export const FETCH_EQUIPOS_FAIL = 'FETCH_EQUIPOS_FAIL';
export const ADD_EQUIPO = 'ADD_EQUIPO';

export const FETCH_STATS_START = 'FETCH_STATS_START';
export const FETCH_STATS_SUCCESS = 'FETCH_STATS_SUCCESS';
export const FETCH_MY_STATS_SUCCESS = 'FETCH_MY_STATS_SUCCESS';
export const FETCH_STATS_FAIL = 'FETCH_STATS_FAIL';
export const ADD_STATS = 'ADD_STATS';

export const FETCH_JUGADORAS_START = 'FETCH_JUGADORAS_START';
export const FETCH_JUGADORAS_SUCCESS = 'FETCH_JUGADORAS_SUCCESS';
export const FETCH_JUGADORAS_FAIL = 'FETCH_JUGADORAS_FAIL';
export const ADD_JUGADORA = 'ADD_JUGADORA';

export const FETCH_STAFF_START = 'FETCH_STAFF_START';
export const FETCH_STAFF_SUCCESS = 'FETCH_STAFF_SUCCESS';
export const FETCH_STAFF_FAIL = 'FETCH_STAFF_FAIL';
export const ADD_STAFF_MEMBER = 'ADD_STAFF_MEMBER';

export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';